# https://mattvsts.github.io/2020/01/07/create-a-build-matrix-with-azure-pipelines/

trigger:
- master

strategy:
  matrix:
    'Ubuntu 14.04 and sqlite':
      TEST_IMAGE="ubuntu:14.04"
      TEST_SCRIPT="debian_prepare && install_w3top"
    'CentOS 7.6 and sqlite (curl)':
      TEST_IMAGE="centos:7.0.1406"
      TEST_SCRIPT="centos_wget_only && install_w3top"
    'Ubuntu 18.04 and sqlite':
      TEST_IMAGE="ubuntu:18.04"
      TEST_SCRIPT="debian_prepare && install_w3top"

pool:
  vmImage: 'ubuntu-18.04'


steps:

- script: |
    script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
    # Say --Reset-Stopwatch
    Say "Pull $(TEST_IMAGE)"
    docker pull $(TEST_IMAGE)
    Say "Images"
    docker images ls
    Say "env"
    printenv | sort
  displayName: 'Test'
