# https://mattvsts.github.io/2020/01/07/create-a-build-matrix-with-azure-pipelines/
variables:
  VMIMAGE: 'ubuntu-22.04'
  
trigger:
- master

strategy:
  matrix:
    'SystemD Debian 8':
      IMAGE: "jrei/systemd-debian:8"
      SCRIPT: "debian_prepare"
      SYSTEMD: 'True'
      VMIMAGE: 'ubuntu-20.04'
    'SystemD Debian 9':
      IMAGE: "jrei/systemd-debian:9"
      SCRIPT: "debian_prepare"
      SYSTEMD: 'True'
      VMIMAGE: 'ubuntu-20.04'
    'SystemD Debian 10':
      IMAGE: "jrei/systemd-debian:10"
      SCRIPT: "debian_prepare"
      SYSTEMD: 'True'
      VMIMAGE: 'ubuntu-20.04'
    'SystemD Debian 11':
      IMAGE: "jrei/systemd-debian:11"
      SCRIPT: "debian_prepare"
      SYSTEMD: 'True'
      VMIMAGE: 'ubuntu-20.04'

    'SystemD Fedora 26':
      IMAGE: "devizervlad/systemd-on-fedora:26"
      SCRIPT: "sudo dnf update --nogpgcheck -y -q; echo"
      SystemD: 'True'
    'SystemD Fedora 31':
      IMAGE: "devizervlad/systemd-on-fedora:31"
      SCRIPT: "sudo dnf update --nogpgcheck -y -q; echo"
      SystemD: 'True'


    # alpine needs new MonoPosixH native so
    # 'Alpine 3.5':
    #   IMAGE: "alpine:3.5"
    #   SCRIPT: "alpine_prepare"
    # 'Alpine 3.6':
    #   IMAGE: "alpine:3.6"
    #   SCRIPT: "alpine_prepare"
    # 'Alpine 3.7':
    #   IMAGE: "alpine:3.7"
    #   SCRIPT: "alpine_prepare"
    # 'Alpine 3.8':
    #   IMAGE: "alpine:3.8"
    #   SCRIPT: "alpine_prepare"
    # 'Alpine 3.12':
    #   IMAGE: "alpine:3.12"
    #   SCRIPT: "alpine_prepare"
    # 'Alpine 3.14':
    #   IMAGE: "alpine:3.14"
    #   SCRIPT: "alpine_prepare"

    # 'ARMv7 Ubuntu Core 20.04':
    #   IMAGE: "multiarch/ubuntu-core:armhf-focal"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Ubuntu Core 18.04':
    #   IMAGE: "multiarch/ubuntu-core:armhf-bionic"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Ubuntu Core 16.04':
    #   IMAGE: "multiarch/ubuntu-core:armhf-xenial"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Ubuntu Core 14.04':
    #   IMAGE: "multiarch/ubuntu-core:armhf-trusty"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'

    # 'ARMv7 Ubuntu 20.04':
    #   IMAGE: "multiarch/ubuntu-debootstrap:armhf-focal"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Ubuntu 18.04':
    #   IMAGE: "multiarch/ubuntu-debootstrap:armhf-bionic"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Ubuntu 16.04':
    #   IMAGE: "multiarch/ubuntu-debootstrap:armhf-xenial"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Ubuntu 14.04':
    #   IMAGE: "multiarch/ubuntu-debootstrap:armhf-trusty"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'

    # 'ARMv7 Debian 11':
    #   IMAGE: "multiarch/debian-debootstrap:armhf-bullseye"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Debian 10':
    #   IMAGE: "multiarch/debian-debootstrap:armhf-buster"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Debian 9':
    #   IMAGE: "multiarch/debian-debootstrap:armhf-stretch"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 Debian 9':
    #   IMAGE: "multiarch/debian-debootstrap:armhf-stretch"
    #   SCRIPT: "debian_prepare"
    #   Multiarch: 'True'
    # 'ARMv7 OpenSUSE 42':
    #   IMAGE: "arm32v7/opensuse"
    #   SCRIPT: "opensuse_prepare"
    #   QEMUVOL: '/usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static'
    # 'ARMv7 Ubuntu 20.04':
    #   IMAGE: "arm32v7/ubuntu:20.04"
    #   SCRIPT: "debian_prepare"
    #   QEMUVOL: '/usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static'
    'ARMv7 Debian 8':
      IMAGE: "multiarch/debian-debootstrap:armhf-jessie"
      SCRIPT: "debian_prepare"
      Multiarch: 'True'
    'ARMv7 Debian 9':
      IMAGE: "multiarch/debian-debootstrap:armhf-stretch"
      SCRIPT: "debian_prepare"
      Multiarch: 'True'
    'ARMv7 Debian 10':
      IMAGE: "multiarch/debian-debootstrap:armhf-buster"
      SCRIPT: "debian_prepare"
      Multiarch: 'True'
    'ARMv7 Debian 11':
      IMAGE: "multiarch/debian-debootstrap:armhf-bullseye"
      SCRIPT: "debian_prepare"
      Multiarch: 'True'
    'ARM-64 Debian 9':
      IMAGE: "multiarch/debian-debootstrap:arm64-stretch"
      SCRIPT: "debian_prepare"
      Multiarch: 'True'

    'CentOS 6.10 and MySQL 5.1 (wget)':
      IMAGE: "centos:6.10"
      SCRIPT: "mysql_51_on_centos_6; centos_wget_only"
    'CentOS 6.10 and PostgreSQL 11.4 (curl)':
      IMAGE: "centos:6.10"
      SCRIPT: "pg_11_on_centos_6 && centos_curl_only"
    'CentOS 7.6 and sqlite (curl)':
      IMAGE: "centos:7.0.1406"
      SCRIPT: "centos_wget_only"
    'CentOS 8':
      IMAGE: "centos:8"
      SCRIPT: "prepare_centos_8; centos_curl_only"

    'OpenSUSE Leap 42':
      IMAGE: 'opensuse/leap:42'
      SCRIPT: 'opensuse_prepare'
    'OpenSUSE Leap 15':
      IMAGE: 'opensuse/leap:15'
      SCRIPT: 'opensuse_prepare'
    'OpenSUSE Tumbleweed':
      IMAGE: 'opensuse/tumbleweed'
      SCRIPT: 'opensuse_prepare'

    'Gentoo (portage)':
      IMAGE: 'gentoo/portage'
      SCRIPT: 'gentoo_prepare; HTTP_HOST="+"; export HTTP_HOST'
    'Gentoo (stage3)':
      IMAGE: 'gentoo/stage3'
      SCRIPT: 'gentoo_prepare; HTTP_HOST="+"; export HTTP_HOST'
    'Arch':
      IMAGE: 'archlinux:base'
      SCRIPT: 'pacman -Sy --noconfirm sudo tar'
    'Manjaro':
      IMAGE: 'manjarolinux/base'
      SCRIPT: 'pacman -Syu --noconfirm haveged; pacman -Sy --noconfirm sudo tar'
    'Amazon Linux v1':
      IMAGE: "amazonlinux:1"
      SCRIPT: "yum install tar sudo -y"
    'Amazon Linux v2':
      IMAGE: "amazonlinux:2"
      SCRIPT: "yum install tar sudo -y"
    'Debian 8.9':
      IMAGE: "debian:8.9"
      SCRIPT: "debian_prepare"
    'Debian 9':
      IMAGE: "debian:9"
      SCRIPT: "debian_prepare"
    'Debian 10':
      IMAGE: "debian:10"
      SCRIPT: "debian_prepare"
    'Debian 12':
      IMAGE: "debian:12"
      SCRIPT: "debian_prepare"
    'Debian 11':
      IMAGE: "debian:11"
      SCRIPT: "debian_prepare"
    'Ubuntu 23.10':
      IMAGE: "ubuntu:23.10"
      SCRIPT: "debian_prepare"
    'Ubuntu 23.04':
      IMAGE: "ubuntu:23.04"
      SCRIPT: "debian_prepare"
    'Ubuntu 22.04':
      IMAGE: "ubuntu:22.04"
      SCRIPT: "debian_prepare"
    'Ubuntu 20.04':
      IMAGE: "ubuntu:18.04"
      SCRIPT: "debian_prepare"
    'Ubuntu 18.04':
      IMAGE: "ubuntu:18.04"
      SCRIPT: "debian_prepare"
    'Ubuntu 16.04':
      IMAGE: "ubuntu:16.04"
      SCRIPT: "debian_prepare"
    'Ubuntu 14.04':
      IMAGE: "ubuntu:14.04"
      SCRIPT: "debian_prepare"
    'Fedora 24':
      IMAGE: "fedora:24"
      SCRIPT: "fedora_prepare"
    'Fedora 25':
      IMAGE: "fedora:25"
      SCRIPT: "fedora_prepare"
    'Fedora 26':
      IMAGE: "fedora:26"
      SCRIPT: "fedora_prepare"
    'Fedora 32':
      IMAGE: "fedora:32"
      SCRIPT: "fedora_prepare"

    'Fedora 33':
      IMAGE: "fedora:33"
      SCRIPT: "fedora_prepare"
    'Fedora 34':
      IMAGE: "fedora:34"
      SCRIPT: "fedora_prepare"
    'Fedora 35':
      IMAGE: "fedora:35"
      SCRIPT: "fedora_prepare"
    'Fedora 36':
      IMAGE: "fedora:36"
      SCRIPT: "fedora_prepare"
    'Fedora 37':
      IMAGE: "fedora:37"
      SCRIPT: "fedora_prepare"
    'Fedora 38':
      IMAGE: "fedora:38"
      SCRIPT: "fedora_prepare"
    'Fedora 39':
      IMAGE: "fedora:39"
      SCRIPT: "fedora_prepare"

# timeoutInMinutes: 25
pool:
  vmImage: '$(VMIMAGE)'

steps:

- script: |
    script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
    Say --Reset-Stopwatch
    Say "Register qemu user static"
    time docker run --rm --privileged multiarch/qemu-user-static:register --reset
  condition: ne(variables.Multiarch, '')
  displayName: 'QEMU'

- script: |
    script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
    Say "IP"
    ip addr show
    Say "if config"
    sudo ifconfig -a
    Say "Reconfigure NET"
    echo '
    net.ipv4.ip_forward = 1
    vm.swappiness = 20
    fs.inotify.max_user_watches = 524288
    net.ipv6.conf.all.disable_ipv6 = 1
    net.ipv6.conf.default.disable_ipv6 = 1
    net.ipv6.conf.lo.disable_ipv6 = 1
    ' | sudo tee -a /etc/sysctl.conf
    sudo sysctl -p
    sudo sysctl -p --system

    Say "FINAL IP"
    ip addr show
    Say "FINAL if config"
    sudo ifconfig -a
  displayName: 'NET'

- script: |
    set -e
    set -u

    script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null
    Say --Reset-Stopwatch

    if [[ -n "${QEMUVOL:-}" ]]; then
      Say "Install qemu-user-static"
      sudo apt-get update -qq
      smart-apt-install qemu-user-static
    fi

    Say "Pull $(IMAGE)"
    docker pull $(IMAGE)
    if [[ "${SYSTEMD:-}" == "True" ]]; then
      Say "Start SYSTEM-D image $(IMAGE)"
      docker run --privileged -t --rm -d --hostname w3top-systemd-container --name w3top -p "5050:5050" --cap-add SYS_ADMIN -v "/sys/fs/cgroup:/sys/fs/cgroup:ro" "$IMAGE"
    elif [[ -n "${QEMUVOL:-}" ]]; then
      Say "Start image $(IMAGE) via qemu [$QEMUVOL]"
      docker run --privileged -t --rm -d --hostname w3top-container --name w3top -p "5050:5050" -v $QEMUVOL "$IMAGE" sh -c "while true; do sleep 42; done"
    else
      Say "Start image $(IMAGE)"
      docker run --privileged -t --rm -d --hostname w3top-container --name w3top -p "5050:5050" "$IMAGE" sh -c "while true; do sleep 42; done"
    fi
    for cmd in Say try-and-retry; do
      docker cp /usr/local/bin/$cmd w3top:/usr/local/bin/$cmd
    done
    if [[ "$IMAGE" == alpine* ]]; then docker exec -t w3top sh -c "apk update --no-progress; apk add --no-progress curl tar sudo bzip2 bash; apk add --no-progress bash icu-libs ca-certificates krb5-libs libgcc libstdc++ libintl libstdc++ tzdata userspace-rcu zlib openssl; echo"; fi
    
    Say "Version for $(IMAGE)"
    docker exec -t w3top bash -c 'cat /etc/*release; mkdir -p /etc/init.d;'
    # docker exec -t w3top bash -c 'script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash >/dev/null'

    Say "ADJUST OS REPO"
    utils_master_url=https://raw.githubusercontent.com/devizer/NetCore.CaValidationLab/master/4gcc/build-gcc-utilities.sh
    try-and-retry curl -kSL -o /tmp/build-gcc-utilities.sh "${utils_master_url}"
    docker cp /tmp/build-gcc-utilities.sh w3top:/tmp/build-gcc-utilities.sh
    docker exec -t w3top bash -c "source /tmp/build-gcc-utilities.sh; adjust_os_repo || true; test -s /etc/apt/sources.list && Say 'Debian Container Sources' && cat /etc/apt/sources.list" || true

    Say "Install sudo, tar, curl|wget, etc into the container"
    cat tests/*.sh > tests/test-sources.sh; chmod +x tests/test-sources.sh
    docker cp tests/test-sources.sh w3top:/test-sources.sh
    docker exec -t w3top bash -c "
        echo HOME: \$HOME; 
        source /test-sources.sh;
        $SCRIPT
    "
  displayName: 'Run Container'

- script: |
    set -e
    set -u
    function wait_for_http() {
      u="$1"; t=30; 
      printf "Waiting for [$u] during $t seconds ..."
      while [ $t -ge 0 ]; do t=$((t-1)); curl --connect-timeout 3 -skf "$u" >/dev/null && printf " OK\n"; if [ $? -eq 0 ]; then return; fi; printf "."; sleep 1; done
      printf " FAIL\n";
    }

    docker exec -t w3top bash -c "
        source /test-sources.sh;
        Say 'INSTALLING W3Top' &&
        install_w3top &&
        Say 'TEST FINISHED. Checking app health.'
    "
    
    Say "Wait for w3top via http://localhost:5050 for $(IMAGE)"
    wait_for_http http://localhost:5050
    
    # check service status
    if [[ "${SYSTEMD:-}" == True ]]; then
      Say "SystemD w3top.service status"
      docker exec w3top bash -e -c "set -o pipefail; systemctl status w3top.service | head -30" || exit 240
    fi
    
    Say "Headers"
    curl -I http://localhost:5050 || curl -I http://localhost:5050 || exit 250

  displayName: 'w3top'

- script: |
   sleep 11
   docker exec -t w3top bash -c "set -o pipefail; if [[ -f /etc/systemd/system/w3top.service ]]; then sudo journalctl -u w3top.service | head -29999; else cat /tmp/w3top.log; fi" |
   tee $SYSTEM_ARTIFACTSDIRECTORY/w3top.log

   docker cp w3top:/etc/init.d/w3top $SYSTEM_ARTIFACTSDIRECTORY/w3top.init.sh
   docker cp w3top:/etc/systemd/system/w3top.service $SYSTEM_ARTIFACTSDIRECTORY/w3top.service.ini
   docker cp w3top:/test-sources.sh $SYSTEM_ARTIFACTSDIRECTORY/test-sources.sh
   true
  condition: succeededOrFailed()
  displayName: 'Grab w3top log'

- task: PublishBuildArtifacts@1
  condition: succeededOrFailed()
  inputs:
    pathtoPublish: '$(System.ARTIFACTSDIRECTORY)'
    artifactName: '$(Agent.JobName)'

